export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const CART_EMPTY = 'CART_EMPTY';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
